### ISSUE TITLE
Contribuam no repositório do partido

### ISSUE THREAD

**Issue by iuriguilherme** [carloscosta/apoio-piratas#5]
https://github.com/piratas/apoio-piratas

O @carloscosta vai atualizar lá o repositório, e lá tem eu e mais pessoas com acesso, da pra dar acesso pra todo mundo.

**Comment by carloscosta** [comment]
resolvido. Fiz o merge de todos os patches que recebi, depois levei um pull request para o repositório do partido. Movendo a Master para lá. Obrigado!
